import '@/styles/globals.css';

import { JSX } from 'react';

import type { Metadata } from 'next';

import { cn } from '@/lib/utils';
import { montserrat } from '@/fonts/fonts';
import { Scroll } from '@/components/atoms';
// import { logger } from '@/lib/utils/misc/logger';
import TanStackProvider from 'src/api/TanStackProvider';
// import { ThemeProvider } from 'next-themes';
import { ThemeProvider } from '@/components/providers/theme-provider';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Cuồng Phim - Watch Movies Online',
};

// logger.info({
//   msg: 'Initializing RootLayout',
//   fileName: 'Rootlayout.tsx',
//   action: 'RootLayout Render',
//   details: {
//     initializingLayout: true,
//     renderingChildrenComponents: true,
//     settingUpThemeProvider: true,
//     settingUpTanStackProvider: true,
//   },
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html suppressHydrationWarning lang="en">
      <Scroll />
      <body
        className={cn(
          'tw-themes antialiased scheme-light dark:scheme-dark',
          `${montserrat.className}`,
        )}
      >
        <ThemeProvider
          disableTransitionOnChange
          enableSystem
          attribute="class"
          defaultTheme="system"
        >
          <TanStackProvider>{children}</TanStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
